<?php if (isset($_SESSION['pedido']) && $_SESSION['pedido'] == 'complete') : ?>
    <h1>Tu pedido se ha confirmado</h1>
    <p>
        Tu pedido ha sido guardado con éxito, una vez que realices la transferencia
        bancaria con el costo del pedido, será procesado y enviado.
    </p>
    <?php if (isset($pedido)) : ?>
        <h3 id="pedido_titulo">Datos del Pedido</h3>
        <p class="datos_pedido">Número de pedido: <?= $pedido->id ?></p>
        <p class="datos_pedido">Total a pagar:$<?= $pedido->coste ?></p>
        <table class="pedido_confirmado">
            <tr>
                <th>Imagen</th>
                <th>Producto</th>
                <th>Cantidad</th>
                <th>Precio</th>
            </tr>
            <?php while ($producto = $productos->fetch_object()) : ?>
                <tr>
                    <td>
                        <?php if ($producto->imagen != null) : ?>
                            <img src="<?= BASE_URL ?>upload/images/<?= $producto->imagen ?>" class="img_carrito">
                        <?php else : ?>
                            <img src="<?= BASE_URL ?>assets/img/camiseta.png" class="img_carrito">
                        <?php endif; ?>
                    </td>
                    <td><a href="<?= BASE_URL ?>producto/ver&id=<?= $producto->id ?>"><?= $producto->nombre ?></a></td>
                    <td><?= $producto->precio ?></td>
                    <td><?= $producto->unidades ?></td>
                </tr>
            <?php endwhile; ?>
        </table>
    <?php endif ?>
<?php elseif (isset($_SESSION['pedido']) && $_SESSION['pedido'] != 'complete') : ?>
    <h1>Tu pedido No ha podido procesarse</h1>
<?php endif; ?>