<?php if (isset($_SESSION['identity'])) : ?>
    <h1>Pedidos</h1>
    <p>
        <a href="<?= BASE_URL ?>carrito/index">Ver los productos y el precio del Pedido</a>
    </p>
    <h3>Dirección para el envio:</h3>
    <form action="<?= BASE_URL . 'pedido/add' ?>" method="POST">
        <label for="provincia">Provincia:</label>
        <input type="text" name="provincia" required>

        <label for="localidad">Ciudad:</label>
        <input type="text" name="localidad" required>

        <label for="direccion">Dirección:</label>
        <input type="text" name="direccion" required>

        <input type="submit" value="Confirmar pedido">
    </form>
<?php else : ?>
    <h1>Necesitas esta identificado</h1>
    <p>Necesistas estar logueado en la web para poder realizar tu pedido.</p>
<?php endif; ?>