<h1><i class="fas fa-layer-group"></i>Categorias</h1>

<a href="<?= BASE_URL ?>categoria/crear" class="button button-small">Crear Categoria</a>

<?php if (isset($_SESSION['categoria']) && $_SESSION['categoria'] == 'complete') : ?>
    <br>
    <strong class="alert-green">La categoria se ha creado correctamente</strong>
<?php endif; ?>
<?php Utils::DeleteSession('categoria'); ?>

<table>
    <tr>
        <th>Id</th>
        <th>Nombre</th>
    </tr>
    <?php while ($cat = $categorias->fetch_Object()) : ?>
        <tr>
            <td><?= $cat->id; ?></td>
            <td><?= $cat->nombre; ?></td>
        </tr>
    <?php endwhile; ?>
</table>