<h1>Carrito de la Compra</h1>

<table>
    <tr>
        <th>Imagen</th>
        <th>Nombre</th>
        <th>Precio</th>
        <th>Unidades</th>
    </tr>
    <?php foreach ($carrito as $indice => $elemento) :
        $producto = $elemento['producto'];
        ?>
        <tr>
            <td>
                <?php if ($producto->imagen != null) : ?>
                    <img src="<?= BASE_URL ?>upload/images/<?= $producto->imagen ?>" class="img_carrito">
                <?php else : ?>
                    <img src="<?= BASE_URL ?>assets/img/camiseta.png" class="img_carrito">
                <?php endif; ?>
            </td>
            <td><a href="<?= BASE_URL ?>producto/ver&id=<?= $producto->id ?>"><?= $producto->nombre ?></a></td>
            <td><?= $producto->precio ?></td>
            <td><?= $elemento['unidades'] ?></td>
        </tr>
    <?php endforeach; ?>
</table>
<?php $stats = Utils::statsCarrito(); ?>
<div id="total-carrito" class="clearfix">
    <h3>Precio total: $<?=$stats['total']?></h3>
    <a href="" class="button button-pedido">Realizar Pedido</a>
</div>