<h1>Productos destacados</h1>
<div class="producto">
    <img src="assets/img/camiseta.png" alt="camiseta">
    <h2>Camiseta Azul Ancha</h2>
    <p>30 euros</p>
    <input type="button" value="Comprar" class="button">
</div><!--	fin .product	-->
<div class="producto">
    <img src="assets/img/camiseta.png" alt="camiseta">
    <h2>Camiseta Azul Ancha</h2>
    <p>30 euros</p>
    <input type="button" value="Comprar" class="button">
</div><!--	fin .product	-->
<div class="producto">
    <img src="assets/img/camiseta.png" alt="camiseta">
    <h2>Camiseta Azul Ancha</h2>
    <p>30 euros</p>
    <input type="button" value="Comprar" class="button">
</div><!--	fin .product	-->

