<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link rel="stylesheet" href="<?= BASE_URL ?>/assets/css/normalize.css">
    <link rel="stylesheet" href="<?= BASE_URL ?>/assets/css/styles.css">
    <title>Tienda de Camisetas</title>
</head>

<body>
    <!--	CABECERA	-->
    <header id="header">
        <div id="logo">
            <img src="<?= BASE_URL ?>/assets/img/camiseta.png" alt="Camiseta Logo">

            <a href="<?= BASE_URL ?>">Tienda de camisetas</a>
        </div>
    </header>
    <!--	MENU	-->
    <?php $categorias = Utils::showCategorias(); ?>
    <nav id="menu">
                <ul>
                    <li>
                        <a href="<?=BASE_URL?>">Inicio</a>
                             </li>
                             <?php while ($cat = $categorias->fetch_object()) : ?>
                        <li>
                            <a href="<?=BASE_URL?>categoria/ver&id=<?=$cat->id?>"><?= $cat->nombre; ?></a>
                        </li>
                    <?php endwhile; ?>

                </ul>
                </nav>

                <div id="contenido">