<!--	BARRA LATERAL	-->
<aside id="lateral">
    <div id="carrito" class="bloque-aside">
        <h3>Mi carrito</h3>
        <ul>
            <?php $stats = Utils::statsCarrito(); ?>
            <li><i class="fas fa-tshirt"></i><a href="">Productos(<?= $stats['count'] ?>)</a></li>
            <li><i class="fas fa-money-bill-alt"></i><a href="">Total $<?= $stats['total'] ?></a></li>
            <li><i class="fas fa-shopping-cart"></i><a href="<?= BASE_URL . "carrito/index" ?>">Ver el carrito</a></li>
        </ul>
    </div>
    <div id="login" class="bloque-aside">
        <?php if (!isset($_SESSION['identity'])) : ?>
            <h3>Entrar a la Web</h3>
            <form action="<?= BASE_URL ?>usuario/login" method="post">
                <label for="email">Email</label>
                <input type="email" name="email">
                <label for="password">Contraseña</label>
                <input type="password" name="password">
                <input type="submit" value="Enviar">
            </form>
        <?php else : ?>
            <h3><i class="fas fa-user"></i><?= $_SESSION['identity']->nombre ?> <?= $_SESSION['identity']->apellidos ?></h3>
        <?php endif; ?>

        <ul>
            <?php if (isset($_SESSION['admin'])) : ?>

                <li><i class="fas fa-layer-group"></i><a href="<?= BASE_URL ?>categoria/index">Categorias</a></li>
                <li><i class="fas fa-tshirt"></i><a href="<?= BASE_URL ?>producto/gestion">Productos</a></li>
                <li><i class="fas fa-shopping-cart"></i><a href="<?= BASE_URL ?>pedido/gestion">Pedidos</a></li>
            <?php endif; ?>
            <?php if (isset($_SESSION['identity'])) : ?>
                <li><i class="fas fa-shopping-basket"></i><a href="<?=BASE_URL?>pedido/mis_pedidos">Mis pedidos</a></li>
                <li><i class="fas fa-sign-out-alt"></i><a href="<?= BASE_URL ?>usuario/logout">Cerrar sesión</a></li>
            <?php else : ?>
                <li><i class="fas fa-sign-in-alt"></i><a href="<?= BASE_URL ?>usuario/registro">Registrate aqui</a></li>
            <?php endif; ?>
        </ul>
    </div> <!--	fin #login	-->

</aside>
<!--	CONTENIDO CENTRAL	-->
<div id="central">